### ISSUE TITLE
Get whitelist error 

### ISSUE THREAD

**Issue by suresh-naik-tfs** [cruxinformatics/crux-python#93]
Hi, I followed the documentation to run a sample python script on mac, but getting the following error, any insight would be greatly appreciated:

```
Traceback (most recent call last):
  File "/crux_example/hello.py", line 6, in <module>
    conn = Crux()
           ^^^^^^
  File "/.local/share/virtualenvs/crux_example-cM9mL2JP/lib/python3.11/site-packages/crux/apis.py", line 25, in __init__
    crux_config = CruxConfig(
                  ^^^^^^^^^^^
  File "/.local/share/virtualenvs/crux_example-cM9mL2JP/lib/python3.11/site-packages/crux/_config.py", line 98, in __init__
    retries = Retry(
              ^^^^^^
TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist'

**Comment by asteriske** [comment]
Also experiencing this.

Issue seems to be `urllib3` moving from `method_whitelist` as a param to `allowed_methods`. I tested locally and this swap works, @suresh-naik-tfs you could clone and make this change for yourself to unblock. 

Would be great for Crux to handle this and push a new release!

**Comment by lifeofzi** [comment]
@asteriske - I have raised the code change here [PR-99](https://github.com/cruxinformatics/crux-python/pull/99)
